### ISSUE TITLE
Extension toolbar button icon broken

### ISSUE THREAD

**Issue by DuelMonster** [rioukkevin/vscode-git-commit#4] opened 2020-10-16 13:29 UTC
![image](https://user-images.githubusercontent.com/5095995/96263944-8cc5b400-0fbb-11eb-8845-927d6a3b1bb8.png)
![image](https://user-images.githubusercontent.com/5095995/96263995-a1a24780-0fbb-11eb-8b17-6b01ee18fea6.png)

Icon was fine until latest release 1.1.0

Thought it may have been the theme I was using, but no.

**Comment by rioukkevin** [comment] 2020-10-16 14:31
Oh yeah, I look for it this weekend, thanks for feedback 😉

**Comment by rioukkevin** [comment] 2020-10-19 08:11
I cannot recreate the bug, Wich version of VSCode are you using ? @DuelMonster

**Comment by DuelMonster** [comment] 2020-10-19 08:27
Latest version.  I always keep stuff updated 😉

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

In case it's helpful... Here's the full list of extensions I have installed:

<details><summary>Click to Expand</summary>

```
aaron-bond.better-comments
AkankshaSingh872.case-change
alefragnani.Bookmarks
alexr00.formatallfilesinworkspace
ant-design-vue.vscode-ant-design-vue-helper
aslamanver.vsc-export
be5invis.vscode-icontheme-nomo-dark
christian-kohler.npm-intellisense
codemooseus.vscode-devtools-for-chrome
CoenraadS.bracket-pair-colorizer-2
dariofuzinato.vue-peek
dbaeumer.vscode-eslint
eamodio.gitlens
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
esbenp.prettier-vscode
febean.vue-format
file-icons.file-icons
formulahendry.auto-rename-tag
georgejames.thefoldingstuff
hollowtree.vue-snippets
in4margaret.compareit
ishiyama.vue-autoimport
jeferwang.vscode-setting-export
jock.svg
mrmlnc.vscode-pugbeautify
ms-dotnettools.csharp
ms-vsts.team
msjsdiag.debugger-for-chrome
octref.vetur
peakchen90.vue-beautify
PKief.material-icon-theme
rioukkevin.vscode-git-commit
ryanlaws.toggle-case
sdras.vue-vscode-extensionpack
sdras.vue-vscode-snippets
slevesque.shader
streetsidesoftware.code-spell-checker
Strum355.vscode-mc-shader
sysoev.language-stylus
titiaiev.vue-docs
tombonnike.vscode-status-bar-format-toggle
wmaurer.vscode-jumpy
xabikos.JavaScriptSnippets
yuchiu2002.default-material-dark-theme
```
</details>

**Comment by rioukkevin** [comment] 2020-10-19 13:11
Hmm okay, same as me, possibly a conflict with an other extension, I'll try it

**Comment by DuelMonster** [comment] 2020-10-19 13:22
I just tried disabling all my extensions, restarting and then re-enabling GCM but got the same issue 😥

**Comment by rioukkevin** [comment] 2020-10-19 13:58
Arf

**Comment by rioukkevin** [comment] 2020-10-20 07:36
I update icon this week, I have no lead

**Comment by rioukkevin** [comment] 2020-10-20 20:38
I updated the extension to V1.1.1 minutes ago, can you try it and give me feedback ? 😉

**Comment by DuelMonster** [comment] 2020-10-21 09:17
Unfortunately it hasn't made any difference 😥

I've tried:
Removing my custom settings -> restarting VSCode
Uninstalling the extension -> restarting VSCode
Reinstalling the extension  -> restarting VSCode

There must be something screwy with my VSCode install.

**Comment by rioukkevin** [comment] 2020-10-21 11:46
I'm not sure it's about your vscode install, a friend got it when using version 0.0.2 or 0.0.3 can you try installing [this extension](https://marketplace.visualstudio.com/items?itemName=rioukkevin.vscode-git-buttons) and say to me if the problem is the same on other icons ?

**Comment by DuelMonster** [comment] 2020-10-21 15:25
![image](https://user-images.githubusercontent.com/5095995/96741546-d34f5000-13b9-11eb-8aa0-6d8dd1e9c319.png)

Those are currently working fine...  🤔

**Comment by rioukkevin** [comment] 2020-10-21 16:04
Hmmm, I'm working on a totally new icon, it will be released with #5 in weeks 😉

**Comment by rioukkevin** [comment] 2020-11-06 13:47
I found why icons are not working, btw I update icon to a totally new one 😋

**Closed as completed by rioukkevin** 2020-11-06 13:47 UTC
Labels: done

**Comment by DuelMonster** [comment] 2020-11-12 17:51
Nice one!  I can confirm my icon has returned 👍

**Comment by rioukkevin** [comment] 2020-11-12 23:03
Nice 😊
